watch_stylesheet: true
watch_config: true
debug: false # Enable debug mode to see more logs
# This komorebi setting will be used for tray context menu.
# If you don't use komorebi, you can remove this section.
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"
# This is the main configuration file for Yet Another Status Bar (YASB)
bars:
  status-bar:
    enabled: true
    #screens: ['DELL P2419H (1)'] # If you want to show on specific screen
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false 
      acrylic: false 
      dark_mode: false
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 36
    padding:
      top: 4
      left: 4
      bottom: 4
      right: 7
    widgets:
      left:
        [
        "power_menu",
        "disk",
        "wallpapers",
        "cpu",
        "memory",
        "wifi",
        "netspeed",
        "kanata"
        ] 
      center: [
          "komorebi_workspaces",
          "active_window"
        ]
      right:
        [
          "media",
          "volume",
          "weather",
          "clock"
        ]
widgets:
  kanata:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\uf11c</span>{data}"
      label_alt: "{data}"
      class_name: "kanata-widget"
      exec_options:
        run_cmd: "powershell if (Get-Process -Name 'kanata' -ErrorAction SilentlyContinue) {'kanata'} else {'qwerty'}"
        run_interval: 5000
        return_format: "string"
      callbacks:
        on_left: "exec powershell kanata -c $env:USERPROFILE/.config/kanata/kanata.kbd -p 9999" 
        on_right: "exec powershell Stop-Process -Name 'kanata' -Force -ErrorAction SilentlyContinue"

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: ""
      label_alt: ""
      label_no_window: "\udb80\udedc"
      label_icon: true
      label_icon_size: 14
    max_length: 56
    max_length_ellipsis: "..."
    monitor_exclusive: true
    label_shadow:
      enabled: true
      color: "black"
      radius: 3
      offset: [ 1, 1 ]

  media:
      type: "yasb.media.MediaWidget"
      options:
        label: "{title} - {artist}"
        label_alt: "{title}"
        max_field_size:
          label: 20
          label_alt: 30
        show_thumbnail: true
        controls_only: false
        controls_left: true
        hide_empty: true
        thumbnail_alpha: 80
        thumbnail_padding: 8
        thumbnail_corner_radius: 16 # Set to 0 for square corners
        icons:
          prev_track: "\ue892"
          next_track: "\ue893"
          play: "\ue768"
          pause: "\ue769"

  clock:
      type: "yasb.clock.ClockWidget"
      options:
        label: "{%a %d, %b %H:%M}"
        label_alt: "{%A %d %B %Y, %H:%M}"
        #locale: 'en_EN' # Langugae for date, you can set your own, example fr_FR
        timezones: [] #Looking up time zone info from registry
        #timezones: ["America/Montreal"]

  cpu:
      type: "yasb.cpu.CpuWidget"
      options:
        label: "<span>\uf4bc</span> {info[percent][total]}%"
        label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
        update_interval: 2000
        histogram_icons:
          - '\u2581' # 0%
          - '\u2581' # 10%
          - '\u2582' # 20%
          - '\u2583' # 30%
          - '\u2584' # 40%
          - '\u2585' # 50%
          - '\u2586' # 60%
          - '\u2587' # 70%
          - '\u2588' # 80%+
        histogram_num_columns: 8
        callbacks:
          on_right: "exec cmd /c Taskmgr"

  memory:
      type: "yasb.memory.MemoryWidget"
      options:
        label: "<span>\uefc5</span> {virtual_mem_percent}%"
        label_alt: "<span>\uefc5</span> {virtual_mem_free}"
        update_interval: 10000
        callbacks:
          on_right: "exec cmd /c Taskmgr"

  komorebi_workspaces:
      type: "komorebi.workspaces.WorkspaceWidget"
      options:
          label_offline: "Komorebi Offline"
          label_workspace_btn: "\udb81\udc3d"
          label_workspace_active_btn: "\udb81\udc3e"
          label_workspace_populated_btn: "\udb81\udc3e"
          label_default_name: "{index}"
          label_zero_index: false
          hide_empty_workspaces: true
          hide_if_offline: false
          container_padding: 
            top: 0
            left: 8
            bottom: 0
            right: 8

  wifi:
      type: "yasb.wifi.WifiWidget"
      options:
        label: "<span>{wifi_icon}</span>"
        label_alt: "{wifi_name} {wifi_strength}%"
        update_interval: 5000
        callbacks:
          on_left: "exec cmd.exe /c start ms-settings:network"
          on_middle: "do_nothing"
          on_right: "toggle_label"
        ethernet_label: "<span>{wifi_icon}</span>"
        ethernet_label_alt: "<span>{wifi_icon}</span>{ip_addr}"
        ethernet_icon: "\ueba9"
        wifi_icons: [
          "\udb82\udd2e",  # Icon for 0% strength
          "\udb82\udd1f",  # Icon for 1-24% strength
          "\udb82\udd22",  # Icon for 25-49% strength
          "\udb82\udd25",  # Icon for 50-74% strength
          "\udb82\udd28"   # Icon for 75-100% strength
        ]
        label_shadow:
          enabled: true
          color: "black"
          radius: 3
          offset: [ 1, 1 ]

  netspeed:
      type: "yasb.custom.CustomWidget"
      options:
        label: "{data[speed]}"
        label_alt: "{data[ping]}"
        class_name: "netspeed-widget"
        exec_options:
          run_cmd: "powershell $env:USERPROFILE/.config/yasb/netspeed.ps1"
          run_interval: 720000
          return_format: "json"
        callbacks:
          on_left: "toggle_label"
          on_right: "do_nothing"

  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: {conditions}, Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: '3bf4cf9a7c3f40d6b31174128242807'
      update_interval: 600 #Update interval in seconds, Min 600
      hide_decimal: true
      location: "Rio de Janeiro, Rio de Janeiro, BR"
      units: "metric"
      callbacks:
        on_left: "toggle_card"
      icons:
        sunnyDay: "󰖙 "
        clearNight: "󰖔 "
        cloudyDay: "󰖕 "
        cloudyNight: "󰼱 "
        rainyDay: "󰖖 "
        rainyNight: "󰖖 "
        default: "\udb81\udd99"
      weather_card:
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "#45475a"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 48

  volume:
      type: "yasb.volume.VolumeWidget"
      options:
        label: "<span>{icon}</span>{level}"
        label_alt: "{volume}"
        volume_icons:
          - " "  # Icon for muted
          - " "  # Icon for 0-10% volume
          - " "  # Icon for 11-30% volume
          - " "  # Icon for 31-60% volume
          - " "  # Icon for 61-100% volume
        callbacks:
          on_right: "exec cmd.exe /c start ms-settings:sound"

  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "⏻"
        uptime: True
        blur: False
        blur_background: True
        animation_duration: 300 # Milisecond 
        button_row: 3 # Number of buttons in row, min 1 max 5
        buttons:
          lock: ["\uea75","Lock"]
          signout: ["\udb80\udf43","Sign out"]
          #sleep: ["\u23fe","Sleep"]
          shutdown: ["⏻","Shut Down"]
          restart: ["\uead2","Restart"]
          hibernate: ["\uf28e","Hibernate"]
          cancel: ["\udb81\udf3a","Cancel"]
          #force_shutdown: ["\uf011","Force Shut Down"]
          #force_restart: ["\uead2","Force Restart"]
      
  disk:
    type: "yasb.disk.DiskWidget"
    options:
        label: "<span>\uf473</span>"
        label_alt: "<span>\uf473</span>"
        group_label:
          volume_labels: ["C", "D", "E", "F"]
          show_label_name: true 
          blur: True
          round_corners: True
          round_corners_type: "normal"
          border_color: "System"
          alignment: "right"
          direction: "down"
          distance: 6
        callbacks:
          on_left: "toggle_group"
  
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "$env:USERPROFILE/.config/wallpapers" # Example path to folder with images
      change_automatically: false # Automatically change wallpaper
      update_interval: 60 # If change_automatically is true, update interval in seconds
      gallery:
          enabled: true
          blur: true
          image_width: 220
          image_per_page: 8
          show_buttons: false
          orientation: "portrait"
          image_spacing: 8
          lazy_load: true
          lazy_load_delay: 80
          lazy_load_fadein: 400
          image_corner_radius: 20
          enable_cache: true
      run_after: 
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ] 
